---
- name: Config Apache & Firewall
  hosts: nodes
  vars_files:
    - vars/ports.yml
  tasks:
    - name: Installing {{package}} package
      debug:
        msg: Installing {{package}} package
      yum:
        name: {{package}}
        state: present
    - name: Starting {{service}} service
      debug:
        msg: Starting {{service}} service
      service:
        name: {{service}}
        state: started
    - name: Open {{ports}} for web-server access
      firewalld:
        port: {{ports}}
        permanent: true
        state: enabled
  handlers:
    - name: Restart the firewalld service to load in the firewall changes
      service:
        name: firewalld 
        state: restarted
...